apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: log4j2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        capabilities: Seamless Upgrades
        containerImage: quay.io/qiaolingtang/generate-log:latest
        support: Qiaoling Tang
      creationTimestamp: null
      labels:
        name: log4j2
    spec:
      containers:
      - args:
        - /run.sh
        command:
        - /bin/sh
        image: quay.io/qiaolingtang/generate-log:latest
        imagePullPolicy: IfNotPresent
        name: log4j2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/generate-log
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: generate-log
        name: config
